-- MySQL Script generated by MySQL Workbench
-- Sun Nov 16 17:47:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UniformesBambi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `UniformesBambi` ;

-- -----------------------------------------------------
-- Schema UniformesBambi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UniformesBambi` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema uniformes_bambi_pos
-- -----------------------------------------------------
USE `UniformesBambi` ;

-- -----------------------------------------------------
-- Table `UniformesBambi`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniformesBambi`.`Producto` ;

CREATE TABLE IF NOT EXISTS `UniformesBambi`.`Producto` (
  `id_producto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(100) NULL,
  `descripcion_producto` VARCHAR(255) NULL,
  `categoria` ENUM('escolar', 'deportiva', 'otra') NULL,
  `precio` DECIMAL(10,2) NULL,
  `estado` ENUM('activo', 'inactivo') NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniformesBambi`.`VariacionProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniformesBambi`.`VariacionProducto` ;

CREATE TABLE IF NOT EXISTS `UniformesBambi`.`VariacionProducto` (
  `id_variacion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `talla` VARCHAR(10) NULL,
  `color` VARCHAR(30) NULL,
  `stock` INT UNSIGNED NULL,
  `Producto_id_producto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_variacion`),
  INDEX `fk_VariacionProducto_Producto_idx` (`Producto_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_VariacionProducto_Producto`
    FOREIGN KEY (`Producto_id_producto`)
    REFERENCES `UniformesBambi`.`Producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniformesBambi`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniformesBambi`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `UniformesBambi`.`Cliente` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(50) NULL,
  `telefono_cliente` VARCHAR(15) NULL,
  `correo_cliente` VARCHAR(100) NULL,
  `direccion_cliente` VARCHAR(255) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniformesBambi`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniformesBambi`.`Venta` ;

CREATE TABLE IF NOT EXISTS `UniformesBambi`.`Venta` (
  `id_venta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_venta` VARCHAR(45) NULL,
  `total_venta` DECIMAL(10,2) NULL,
  `Cliente_id_cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_Venta_Cliente1_idx` (`Cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Cliente1`
    FOREIGN KEY (`Cliente_id_cliente`)
    REFERENCES `UniformesBambi`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniformesBambi`.`VentaDetalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniformesBambi`.`VentaDetalle` ;

CREATE TABLE IF NOT EXISTS `UniformesBambi`.`VentaDetalle` (
  `id_detalle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT UNSIGNED NULL,
  `precio_unitario` DECIMAL(10,2) NULL,
  `VariacionProducto_id_variacion` INT UNSIGNED NOT NULL,
  `Venta_id_venta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `fk_VentaDetalle_VariacionProducto1_idx` (`VariacionProducto_id_variacion` ASC) VISIBLE,
  INDEX `fk_VentaDetalle_Venta1_idx` (`Venta_id_venta` ASC) VISIBLE,
  CONSTRAINT `fk_VentaDetalle_VariacionProducto1`
    FOREIGN KEY (`VariacionProducto_id_variacion`)
    REFERENCES `UniformesBambi`.`VariacionProducto` (`id_variacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VentaDetalle_Venta1`
    FOREIGN KEY (`Venta_id_venta`)
    REFERENCES `UniformesBambi`.`Venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniformesBambi`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniformesBambi`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `UniformesBambi`.`Usuario` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NULL,
  `contrasena_hash` VARCHAR(255) NULL,
  `rol_usuario` ENUM('admin', 'vendedor', 'otro') NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniformesBambi`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniformesBambi`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `UniformesBambi`.`Empleado` (
  `id_empleado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_empleado` VARCHAR(50) NULL,
  `puesto_empleado` VARCHAR(40) NULL,
  `telefono_empleado` VARCHAR(15) NULL,
  `rol_empleado` ENUM('admin', 'vendedor', 'otro') NULL,
  `Usuario_id_usuario` INT UNSIGNED NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_Empleado_Usuario1_idx` (`Usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `UniformesBambi`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniformesBambi`.`DefectoProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniformesBambi`.`DefectoProducto` ;

CREATE TABLE IF NOT EXISTS `UniformesBambi`.`DefectoProducto` (
  `id_defecto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion_defecto` VARCHAR(255) NULL,
  `fecha_defecto` VARCHAR(45) NULL,
  `VariacionProducto_id_variacion` INT UNSIGNED NOT NULL,
  `Empleado_id_empleado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_defecto`),
  INDEX `fk_DefectoProducto_VariacionProducto1_idx` (`VariacionProducto_id_variacion` ASC) VISIBLE,
  INDEX `fk_DefectoProducto_Empleado1_idx` (`Empleado_id_empleado` ASC) VISIBLE,
  CONSTRAINT `fk_DefectoProducto_VariacionProducto1`
    FOREIGN KEY (`VariacionProducto_id_variacion`)
    REFERENCES `UniformesBambi`.`VariacionProducto` (`id_variacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DefectoProducto_Empleado1`
    FOREIGN KEY (`Empleado_id_empleado`)
    REFERENCES `UniformesBambi`.`Empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniformesBambi`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniformesBambi`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `UniformesBambi`.`Proveedor` (
  `id_proveedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_proveedor` VARCHAR(50) NULL,
  `telefono_proveedor` VARCHAR(15) NULL,
  `correo_proveedor` VARCHAR(50) NULL,
  `direccion_proveedor` VARCHAR(255) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniformesBambi`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniformesBambi`.`Compra` ;

CREATE TABLE IF NOT EXISTS `UniformesBambi`.`Compra` (
  `id_compra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_compra` VARCHAR(45) NULL,
  `total_compra` DECIMAL(10,2) NULL,
  `Proveedor_id_proveedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_Compra_Proveedor1_idx` (`Proveedor_id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Proveedor1`
    FOREIGN KEY (`Proveedor_id_proveedor`)
    REFERENCES `UniformesBambi`.`Proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniformesBambi`.`CompraDetalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniformesBambi`.`CompraDetalle` ;

CREATE TABLE IF NOT EXISTS `UniformesBambi`.`CompraDetalle` (
  `id_compra_detalle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT UNSIGNED NULL,
  `preciounitario` DECIMAL(10,2) NULL,
  `VariacionProducto_id_variacion` INT UNSIGNED NOT NULL,
  `Compra_id_compra` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_compra_detalle`),
  INDEX `fk_CompraDetalle_VariacionProducto1_idx` (`VariacionProducto_id_variacion` ASC) VISIBLE,
  INDEX `fk_CompraDetalle_Compra1_idx` (`Compra_id_compra` ASC) VISIBLE,
  CONSTRAINT `fk_CompraDetalle_VariacionProducto1`
    FOREIGN KEY (`VariacionProducto_id_variacion`)
    REFERENCES `UniformesBambi`.`VariacionProducto` (`id_variacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CompraDetalle_Compra1`
    FOREIGN KEY (`Compra_id_compra`)
    REFERENCES `UniformesBambi`.`Compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
